[package]
name = "camera"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net"] }

[dev-dependencies]
tower = { version = "0.5.3", features = ["util"] }
