use std::env;
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let repo_root = manifest_dir
        .parent()
        .ok_or_else(|| io::Error::other("backend crate should have a repository root parent"))?;
    let proto_root = repo_root.join("api/proto");
    let island_root = repo_root.join("frontend/src/islands");
    let protos = collect_proto_files(&proto_root)?;
    generate_island_types(&island_root)?;

    if protos.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            format!("no .proto files found under {}", proto_root.display()),
        )
        .into());
    }

    println!("cargo:rerun-if-changed={}", proto_root.display());
    println!("cargo:rerun-if-changed={}", island_root.display());

    // Props contracts are serialized into `solid-props` JSON, so the browser-facing proto package
    // needs serde support with camelCase keys for the island runtime.
    tonic_prost_build::configure()
        .message_attribute(
            ".props.v1",
            "#[derive(serde::Serialize, serde::Deserialize)] #[serde(rename_all = \"camelCase\")]",
        )
        .compile_protos(&protos, &[proto_root])?;

    Ok(())
}

fn collect_proto_files(dir: &Path) -> io::Result<Vec<PathBuf>> {
    fn visit(dir: &Path, protos: &mut Vec<PathBuf>) -> io::Result<()> {
        for entry in fs::read_dir(dir)? {
            let path = entry?.path();

            if path.is_dir() {
                visit(&path, protos)?;
            } else if path.extension().is_some_and(|ext| ext == "proto") {
                protos.push(path);
            }
        }

        Ok(())
    }

    let mut protos = Vec::new();
    visit(dir, &mut protos)?;
    protos.sort();
    Ok(protos)
}

fn generate_island_types(dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let island_names = collect_island_names(dir)?;
    let out_path = PathBuf::from(env::var("OUT_DIR")?).join("generated_islands.rs");
    let mut generated = fs::File::create(out_path)?;

    writeln!(
        generated,
        "// @generated by build.rs from frontend/src/islands/*.tsx"
    )?;

    for island_name in island_names {
        writeln!(
            generated,
            "pub struct {0};\nimpl crate::http::client::island_host::IslandName for {0} {{\n    const NAME: &'static str = \"{0}\";\n}}\n",
            island_name,
        )?;
    }

    Ok(())
}

fn collect_island_names(dir: &Path) -> io::Result<Vec<String>> {
    let mut island_names = Vec::new();

    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();

        if !path.is_file() || path.extension().is_none_or(|ext| ext != "tsx") {
            continue;
        }

        if path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name.ends_with(".test.tsx"))
        {
            continue;
        }

        let island_name = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "invalid island filename"))?;

        if !is_valid_rust_type_name(island_name) {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!("island file `{island_name}` is not a valid Rust type name"),
            ));
        }

        island_names.push(island_name.to_owned());
    }

    island_names.sort();
    Ok(island_names)
}

fn is_valid_rust_type_name(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };

    (first == '_' || first.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}
