[package]
name = "video-analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
axum = { version = "0.8.8", features = ["multipart"] }
axum-htmx = "0.8.1"
envy = "0.4.2"
hypertext = { git = "https://github.com/vidhanio/hypertext", features = ["htmx"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = ["full"] }
surrealdb = { version = "3.0.5", features = ["kv-mem", "kv-surrealkv"] }

[dev-dependencies]
tower = "0.5.3"
