[workspace]
members = [
    "app",
    "camera",
    "synology",
]
resolver = "3"

[workspace.dependencies]
axum = "0.8.9"
thiserror = "2"
tower = { version = "0.5.3", features = ["util"] }
clap = { version = "=4.6.1", features = ["derive"] }
serde_json = "1"


[workspace.dependencies.serde]
version = "1"
features = ["derive"]

[workspace.dependencies.tokio]
version = "1.53.0"
