prepare-camera-video INPUT OUTPUT:
    ffmpeg -i {{quote(INPUT)}} -map 0:v:0 -an \
      -vf "fps=15,scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2" \
      -c:v libx264 -preset slow -crf 28 -profile:v baseline -level:v 3.1 \
      -pix_fmt yuv420p -bf 0 -g 15 -keyint_min 15 -sc_threshold 0 -flags +cgop \
      -movflags +faststart {{quote(OUTPUT)}}

camera-1:
    nix develop --command cargo run -p camera -- --address 127.0.0.1:8080 --rtsp-address 127.0.0.1:8554 --video camera/fixtures/salon-1.mp4

camera-2:
    nix develop --command cargo run -p camera -- --address 127.0.0.1:8081 --rtsp-address 127.0.0.1:8555 --video camera/fixtures/salon-2.mp4

vlc:
    nix develop --command vlc rtsp://127.0.0.1:8554/axis-media/media.amp

app:
    nix develop --command dx serve -p app --desktop

css:
    nix develop --command tailwindcss -i app/tailwind.css -o app/assets/tailwind.css
