[package]
name = "synology"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "time"] }

[dev-dependencies]
serde_json.workspace = true
tower = { workspace = true }
