[package]
name = "synology"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "macros", "net", "process", "rt-multi-thread", "time"] }

[dev-dependencies]
tower = { workspace = true }
